CATALOGUE_HOST: catalogue.backend-{{ env }}.bittu27.site
USER_HOST: user.backend-{{ env }}.bittu27.site
CART_HOST: cart.backend-{{ env }}.bittu27.site
SHIPPING_HOST: shipping.backend-{{ env }}.bittu27.site
PAYMENT_HOST: payment.backend-{{ env }}.bittu27.site
